### PR TITLE
Add C2PA flag

### PR DESCRIPTION
**Pull request by leszko**
Related to https://github.com/livepeer/catalyst-api/pull/931

### CODE REVIEW

**Comment by leszko** [comment]
@iameli Any thoughts why this GH Action is running something related to livepeer-box and why it's failing? 🙃

**Comment by pwilczynskiclearcode** [comment]
It's shows a failure in github action:
```   6 | >>> RUN wget -O - -q https://raw.githubusercontent.com/client9/misspell/master/install-misspell.sh | sh -s -- -b /usr/local/bin/
```

**Comment by hjpotter92** [comment]
> @iameli Any thoughts why this GH Action is running something related to livepeer-box and why it's failing? 🙃

so, it looks like it is picking up the `aws-0b43d73728060b5d9` self-hosted runner, which is `arm64` based. reviewdog/misspell doesn't support arm64. could you change the `[`runs-on` field](https://github.com/livepeer/go-api-client/blob/main/.github/workflows/test.yaml#L12)` to: `linux-amd64` instead?

**Comment by leszko** [comment]
> > @iameli Any thoughts why this GH Action is running something related to livepeer-box and why it's failing? 🙃
> 
> so, it looks like it is picking up the `aws-0b43d73728060b5d9` self-hosted runner, which is `arm64` based. reviewdog/misspell doesn't support arm64. could you change the [`runs-on` field](https://github.com/livepeer/go-api-client/blob/main/.github/workflows/test.yaml#L12) to: `linux-amd64` instead?

But why does `go-api-client` project even run `go-livepeer` GH Action?

**Review by thomshutt — APPROVED** [review]

**Pull request merged**
