### PR TITLE
Add TaskTranscodeFile

### PR DESCRIPTION
**Pull request by leszko**
Related to the updated scheme spec: https://www.notion.so/livepeer/Technical-Design-Doc-1d29ffb74f1e4a8f812f92503fb628e8

### CODE REVIEW

**Review by thomshutt — APPROVED** [review]
LGTM, only concern would be that the naming of `AccessKeyId` and `SecretAccessKey` is quite specific to S3-compatible storage types

**Comment by leszko** [comment]
> LGTM, only concern would be that the naming of `AccessKeyId` and `SecretAccessKey` is quite specific to S3-compatible storage types

Yes, that's a good point. I'll open the discussion in the Technical Doc. Thanks for pointing that out.

**Comment by leszko** [comment]
> LGTM, only concern would be that the naming of `AccessKeyId` and `SecretAccessKey` is quite specific to S3-compatible storage types

Btw. changed to using S3 URL for the Studio <> Task communication, so this discussion is not needed here. But for the API, the question still remains, posted it in the related Notion doc [1]

[1] https://www.notion.so/livepeer/Technical-Design-Doc-1d29ffb74f1e4a8f812f92503fb628e8

**Review by thomshutt — APPROVED** [review]

**Review by victorges — APPROVED** [review]
LGTM

**Pull request merged**
